spring.application.name=product

server.port=9090

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.datasource.url=jdbc:postgresql://localhost:5432/product
spring.datasource.username=postgres
spring.datasource.password=P@sser
spring.jpa.hibernate.ddl-auto=create-drop

jwt.secret=cf0192b405302ba95a6df99f43abf22cc2df48d08213709b13da54a6489891dcb0f8ed91a14dafb888e888dd9a78ee92462d077b7c78f09f49d041eebd4d5680
jwt.expiration=36000000

# Storage Product images
app.upload.dir=/var/www/products/uploads/

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# Enable SQL logging
spring.jpa.show-sql=true

# Format the SQL query output (optional, but makes it more readable)
spring.jpa.properties.hibernate.format_sql=true

# Log SQL queries along with the values of parameters (optional, for Hibernate)
spring.jpa.properties.hibernate.type=trace

# Enable SQL logging for Hibernate
logging.level.org.hibernate.SQL=DEBUG

# Log the parameters of the SQL queries
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

spring.mvc.pathmatch.matching-strategy=path_pattern_parser
logging.level.org.hibernate.orm.jdbc.bind=TRACE
